name: Run E2E Tests

on: [pull_request] ## quando houver uma pull request

jobs:
  run-e2e-tests: ## jobs
    name: Run E2E Tests ## nome job
    runs-on: ubuntu-latest ## maquina para rodar os jobs

    services: ## servi√ßos
      postgres:
        image: bitnami/postgresql ## imagem do banco de dados
        ports:
          - 5432:5432 ## porta que vai rodar
        env:
          POSTGRESQL_USERNAME: docker ## username do banco
          POSTGRESQL_PASSWORD: docker ## senha do banco
          POSTGRESQL_DATABASE: fitmap ## nome do banco

    steps:
      - uses: actions/checkout@v3 ## baixar o c√≥digo da aplica√ß√£o

      - uses: actions/setup-node@v3 ## utilizar o node
        with:
          node-version: 18 ## vers√£o do node
          cache: 'npm' ## para armezanar o cahche das depend√™cias

      - run: npm install -f ## comando para instalar as depend√™cias

      - run: npx prisma generate ## üîπ Gera o Prisma Client com os bin√°rios corretos

      - run: npm run test:e2e ## comando para roda os testes √∫nitarios da aplica√ß√£o
        env:
          JWT_SECRET: testing
          DATABASE_URL: 'postgresql://docker:docker@localhost:5432/fitmap?schema=public'
